apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  serviceName: {{ include "mongo.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 27017
